# Generated by Django 2.2.1 on 2019-06-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='スラグ')),
                ('turn', models.CharField(choices=[('player1', 'player1'), ('player2', 'player2')], max_length=10, verbose_name='プレイヤーターン')),
                ('winner', models.CharField(choices=[('player1', 'player1'), ('player2', 'player2'), ('draw', 'draw'), ('empty', 'empty')], default='empty', max_length=10, verbose_name='勝者')),
                ('_board', models.TextField(verbose_name='盤面')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
