version: "3"
services:
  api:
    build: ./api
    container_name: "othello-api"
    volumes:
      - ./api:/usr/src/app
    ports:
      - "8000:8000"
    command: sh utils/startapp.dev.sh
    links:
      - db:db
      - cache:cache
    tty: true
    stdin_open: true
  db:
    build: ./db
    container_name: "othello-api-db"
    volumes:
      - ./db/datadir:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=eeYuji6Cvu4lieY6
      - MYSQL_DATABASE=dev_othello_api_db
  cache:
    image: redis:3.2.11
    container_name: "othello-api-cache"
    expose:
      - "6379"
